# Generated by Django 5.2.16 on 2026-07-26 03:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.TextField(unique=True, verbose_name='Telefono E.164 o identidad')),
                ('nombre_alias', models.TextField(blank=True, null=True, verbose_name='Alias para mostrar')),
                ('estado', models.TextField(choices=[('activo', 'Activa'), ('suspendido', 'Suspendida'), ('eliminado', 'Eliminada')], default='activo')),
                ('motivo_suspension', models.TextField(blank=True, null=True)),
                ('suspendido_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Apoderado',
                'verbose_name_plural': 'Apoderados',
                'db_table': 'asis_apoderado',
                'constraints': [models.CheckConstraint(condition=models.Q(('estado__in', ['activo', 'suspendido', 'eliminado'])), name='asis_apoderado_estado_valido')],
            },
        ),
        migrations.CreateModel(
            name='IntentoLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.TextField(verbose_name='Hash de la credencial')),
                ('ip', models.TextField(blank=True, null=True)),
                ('exitoso', models.BooleanField(default=False)),
                ('ocurrido_en', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Intento de login',
                'verbose_name_plural': 'Intentos de login',
                'db_table': 'asis_intento_login',
                'indexes': [models.Index(fields=['clave', 'ocurrido_en'], name='asis_idx_intento_login_clave')],
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.TextField(blank=True, null=True)),
                ('accion', models.TextField()),
                ('detalle', models.JSONField(blank=True, null=True)),
                ('request_id', models.TextField(blank=True, null=True)),
                ('ocurrido_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('apoderado', models.ForeignKey(blank=True, db_column='apoderado_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria', to='cuentas.apoderado')),
            ],
            options={
                'verbose_name': 'Registro de auditoria',
                'verbose_name_plural': 'Auditoria',
                'db_table': 'asis_auditoria',
                'indexes': [models.Index(fields=['accion', 'ocurrido_en'], name='asis_idx_auditoria_accion')],
            },
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.TextField()),
                ('token', models.TextField()),
                ('plataforma', models.TextField(blank=True, choices=[('android', 'Android'), ('ios', 'iOS')], null=True)),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('apoderado', models.ForeignKey(db_column='apoderado_id', on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to='cuentas.apoderado')),
            ],
            options={
                'verbose_name': 'Token de push',
                'verbose_name_plural': 'Tokens de push',
                'db_table': 'asis_push_token',
                'constraints': [models.UniqueConstraint(fields=('apoderado', 'device_id'), name='asis_push_token_unico'), models.CheckConstraint(condition=models.Q(('plataforma__isnull', True), ('plataforma__in', ['android', 'ios']), _connector='OR'), name='asis_push_token_plataforma_valida')],
            },
        ),
        migrations.CreateModel(
            name='SesionActiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.TextField()),
                ('jti', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('modelo', models.TextField(blank=True, null=True)),
                ('sistema_operativo', models.TextField(blank=True, null=True)),
                ('estado', models.TextField(default='active')),
                ('creada_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultima_actividad_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('expira_en', models.DateTimeField()),
                ('apoderado', models.ForeignKey(db_column='apoderado_id', on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='cuentas.apoderado')),
            ],
            options={
                'verbose_name': 'Sesion activa',
                'verbose_name_plural': 'Sesiones activas',
                'db_table': 'asis_sesion_activa',
                'indexes': [models.Index(condition=models.Q(('estado', 'active')), fields=['expira_en'], name='asis_idx_sesion_expira')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'active')), fields=('apoderado',), name='asis_uniq_sesion_activa')],
            },
        ),
        migrations.CreateModel(
            name='TransferenciaSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_device_id', models.TextField(blank=True, null=True)),
                ('to_device_id', models.TextField()),
                ('estado', models.TextField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('expired', 'Expirada')], default='pending')),
                ('creada_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('expira_en', models.DateTimeField()),
                ('apoderado', models.ForeignKey(db_column='apoderado_id', on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='cuentas.apoderado')),
            ],
            options={
                'verbose_name': 'Transferencia de sesion',
                'verbose_name_plural': 'Transferencias de sesion',
                'db_table': 'asis_transferencia_sesion',
                'constraints': [models.CheckConstraint(condition=models.Q(('estado__in', ['pending', 'approved', 'rejected', 'expired'])), name='asis_transferencia_estado_valido'), models.UniqueConstraint(condition=models.Q(('estado', 'pending')), fields=('apoderado',), name='asis_uniq_transferencia_pendiente')],
            },
        ),
    ]
