# Generated by Django 5.2.16 on 2026-08-13 20:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.TextField(choices=[('android', 'Android'), ('ios', 'iOS')], unique=True)),
                ('min_soportada', models.PositiveIntegerField(default=1)),
                ('ultima_disponible', models.PositiveIntegerField(default=1)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('url_tienda', models.TextField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Versión de app',
                'verbose_name_plural': 'Versiones de app',
                'db_table': 'asis_app_version',
                'constraints': [models.CheckConstraint(condition=models.Q(('min_soportada__lte', models.F('ultima_disponible'))), name='asis_app_version_min_coherente')],
            },
        ),
    ]
