# Generated by Django 5.2.16 on 2026-07-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.TextField(help_text='Telefono del apoderado normalizado con apps.common.phone.', verbose_name='Telefono E.164')),
                ('tenant_id', models.TextField(verbose_name='Colegio (tenant)')),
                ('id_estudiante', models.IntegerField(verbose_name='Id del estudiante en su colegio')),
                ('codigo_barras', models.TextField(verbose_name='Documento del estudiante')),
                ('nombre_estudiante', models.TextField(verbose_name='Nombre del estudiante')),
                ('grado', models.TextField(blank=True, null=True)),
                ('seccion', models.TextField(blank=True, null=True)),
                ('nivel', models.TextField(blank=True, null=True)),
                ('relacion', models.TextField(blank=True, default='apoderado', null=True)),
                ('origen', models.TextField(blank=True, choices=[('resuelto_automatico', 'Resuelto automaticamente desde la BD del colegio'), ('registrado_admin', 'Registrado a mano por un administrador del canal')], null=True)),
                ('estado_vinculo', models.TextField(blank=True, default='activo', null=True)),
                ('sincronizado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Vinculo del directorio',
                'verbose_name_plural': 'Directorio telefonico',
                'db_table': 'asis_directorio',
                'indexes': [models.Index(fields=['telefono'], name='asis_idx_directorio_telefono')],
                'constraints': [models.UniqueConstraint(fields=('telefono', 'tenant_id', 'id_estudiante'), name='asis_directorio_unico'), models.CheckConstraint(condition=models.Q(('origen__isnull', True), ('origen__in', ['resuelto_automatico', 'registrado_admin']), _connector='OR'), name='asis_directorio_origen_valido')],
            },
        ),
    ]
